services:
  postgres-primary:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: vnu
      POSTGRES_PASSWORD: vnu_secret
      POSTGRES_DB: vnu_exam
    volumes:
      - pg-primary:/var/lib/postgresql/data
      - ./postgres/primary.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
  postgres-replica:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: vnu
      POSTGRES_PASSWORD: vnu_secret
      POSTGRES_DB: vnu_exam
    volumes:
      - pg-replica:/var/lib/postgresql/data
    depends_on:
      - postgres-primary

  redis:
    image: redis:7-alpine

  api-master:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgresql://vnu:vnu_secret@postgres-primary:5432/vnu_exam
      REDIS_HOST: redis
      NODE_ROLE: master
    depends_on:
      - postgres-primary
      - redis

  api-replica:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgresql://vnu:vnu_secret@postgres-replica:5432/vnu_exam
      REDIS_HOST: redis
      NODE_ROLE: replica
    depends_on:
      - postgres-replica
      - redis

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/ha.conf:/etc/nginx/conf.d/default.conf
      - ../apps/web/student/dist:/usr/share/nginx/html/student
      - ../apps/web/proctor/dist:/usr/share/nginx/html/proctor
      - ../scripts/waiting-room-diagnostic.html:/usr/share/nginx/html/scripts/waiting-room-diagnostic.html:ro
    depends_on:
      - api-master
      - api-replica

volumes:
  pg-primary:
  pg-replica:
